### ISSUE TITLE
Test Case Fails

### ISSUE THREAD

**Issue by srinathganesh** [vstoykov/django-clamd#9]
I ran the code `python3 manage.py test django_clamd.tests`

```
======================================================================
FAIL: test_has_virus (django_clamd.tests.test.VirusValidatorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django_clamd/tests/test.py", line 23, in test_has_virus
    self.assertFalse(form.is_valid())
AssertionError: True is not false

======================================================================
FAIL: test_infinite_stream (django_clamd.tests.test.VirusValidatorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django_clamd/tests/test.py", line 54, in test_infinite_stream
    self.assertGreaterEqual(stream._read_bytes, 5 * 1024 * 1024)
AssertionError: 25600 not greater than or equal to 5242880

Ran 3 tests in 0.010s

FAILED (failures=2)
```

**Comment by vstoykov** [comment]
Hi @srinathganesh and thank you for your interest in `django-clamd`.

I want to ask you for more detail s about your environment because on my end everything is ok. Can you tell which are your OS, Python version and ClamAV version?

**Comment by vstoykov** [comment]
Closing due to inactivity from the reporter
